/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_j3d_device_input_vfx_VFXDriver */

#ifndef _Included_org_j3d_device_input_vfx_VFXDriver
#define _Included_org_j3d_device_input_vfx_VFXDriver
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_j3d_device_input_vfx_VFXDriver
 * Method:    initializeVFX
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_org_j3d_device_input_vfx_VFXDriver_initializeVFX
  (JNIEnv *, jobject);

/*
 * Class:     org_j3d_device_input_vfx_VFXDriver
 * Method:    resetTrackerZero
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_j3d_device_input_vfx_VFXDriver_resetTrackerZero
  (JNIEnv *, jobject);

/*
 * Class:     org_j3d_device_input_vfx_VFXDriver
 * Method:    readTrackerPosition
 * Signature: ([F)V
 */
JNIEXPORT void JNICALL Java_org_j3d_device_input_vfx_VFXDriver_readTrackerPosition
  (JNIEnv *, jobject, jfloatArray);

/*
 * Class:     org_j3d_device_input_vfx_VFXDriver
 * Method:    enableVFXStereo
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_org_j3d_device_input_vfx_VFXDriver_enableVFXStereo
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     org_j3d_device_input_vfx_VFXDriver
 * Method:    disableVFXStereo
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_j3d_device_input_vfx_VFXDriver_disableVFXStereo
  (JNIEnv *, jobject);

/*
 * Class:     org_j3d_device_input_vfx_VFXDriver
 * Method:    shutdown
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_j3d_device_input_vfx_VFXDriver_shutdown
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
