#version 460

#include <MoldSimulation.glincl>
#include <random.glincl>

layout(local_size_x = 1, local_size_y = 1) in;


layout(rgba32f, binding = 0) uniform image2D image;
void main() {
	ivec2 pixel = ivec2(gl_GlobalInvocationID.xy);
	
	vec4 color = imageLoad(image, pixel);
	color.xyz -= vec3(0.01);
	color = clamp(color, vec4(0, 0, 0, 1), vec4(100, 100, 100, 1));
	imageStore(image, pixel, color);
	
	
}